services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000/api
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # Using env_file to load from backend/.env
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
      - postgres

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-ai_reporting}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/Github/data_v4/mongodb
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/Github/data_v4/postgres